### ISSUE TITLE
Type of a licence

### ISSUE THREAD

**Issue by JakoobCZ** [jneilliii/OctoPrint-ipOnConnect#1]
Hi,
is it possible to include your plugin into my company's build, which we will offer to all the users for free? I was looking for an option to display the IP address and your plugin is the best :)
Credits will be included ;)

**Comment by jneilliii** [comment]
Of course.

**Comment by jneilliii** [comment]
I'd be interested in knowing more about the company and what products you offer.

**Comment by JakoobCZ** [comment]
Hi,
I'm working for a company Prusa Research, currently creating an OctoPrint image for RPi Zero W on our printer Original Prusa i3 MK3. We want to help beginners by giving them complete step by step guide and since the Pi Zero W is headless it is quite complicated to get the IP address.

Thanks for letting us using your plugin ;)

**Comment by jneilliii** [comment]
That's awesome, you guys are the ones I feel are leading the industry and it would be an honor to be included.
