### ISSUE TITLE
Prusa does not show any Ip

### ISSUE THREAD

**Issue by joppichristian** [jneilliii/OctoPrint-ipOnConnect#11]
Hi,
I've just installed OctoPrint-ipOnConnect plugin but my Prusa MK3S printer shows only "Prusa i3 MK3S ok."

What should I do? Is there something to set on printer configuration?
 I connected the raspberry with USB.

**Comment by jneilliii** [comment]
Your octoprint needs to be manually configured for auto-connect on server startup and the settings saved from the connection panel and make one successful connection to your printer. Then once you restart your pi, the IP should display.

**Comment by joppichristian** [comment]
Ok thank you! Now it works!
