### ISSUE TITLE
Will only display IP when "Show Hostname" is selected"

### ISSUE THREAD

**Issue by Calibr8tion** [jneilliii/OctoPrint-ipOnConnect#16]
Running 0.2.4

If I select "Show Hostname" it will display the hostname followed by the IP address but my screensize cuts off a portion of the IP address on the screen. example" "octopi 192.168.7"

I'm assuming that de-selecting "show hostname" would only show the IP address, as seen in screenshots. If that's true, it is not showing up at all when its de-selected.

**Comment by jneilliii** [comment]
The ip address is retrieved the same way in either case, so not sure what issue you might be running into. Have you tried adjusting the delay to see if a longer one makes a difference in any way?

**Comment by jneilliii** [comment]
do you have any errors in octoprint.log?
