### ISSUE TITLE
OctoPrint 1.3.8 - Plugin works for WiFi only after OctoPrint has been manually restarted, not on cold boot

### ISSUE THREAD

**Issue by devilhunter84** [jneilliii/OctoPrint-ipOnConnect#2]
Hi there. 

I've seen ipOnConnect has been added to the official OctoPrint plugins repo recently, and installed it on my two Pi's running OctoPi 0.14 and OctoPrint 1.3.8.

It's working, but only once, after the plugin is installed and OctoPrint is restarted. 
After that, i cannot get it to work again anymore. 
Uninstalling the plugin (+OP restart), and reinstalling the plugin (+OP restart), then it works again, only once. Next restart of OctoPrint or even the whole Pi OP connects to the printer automatically, but doesn't display the message onscreen. 

Tried this via a stock 0.14 OctoPi image, and my current image, which has a lot of plugins installed.

I'm using OctoPi's ability to automatically connect to a WiFi hotspot. 
When it's not finding known hotspot, it turns the Pi's WiFi into a hotspot itself
https://medium.com/@kennethjiang/painless-wi-fi-for-octoprint-4e6b68005400

ipOnConnect works in both situations (no known wifi or a local wifi is found), tested that, but again, works only once after it's installed. 

Installed the Plugin from the Plugin interface of Octoprint. 

I'm thinking, perhaps the script to display the message does not get activated on the next start of the Pi?
(only once, after it's been installed)

**Comment by jneilliii** [comment]
It's configured to report via an M117 message on connect to the printer using the event hook [here](https://github.com/jneilliii/OctoPrint-ipOnConnect/blob/f3cea714e4ac972979ad2d3201daa8f989ebaa87/octoprint_ipOnConnect/__init__.py#L20). What happens if you disconnect from the UI and reconnect?

**Comment by devilhunter84** [comment]
Can't believe i didn't think of that. 
Disconnecting via the GUI and reconnecting restarts the Printer and then displays the IP address.

Any leads how to make this work on a cold start?

**Comment by jneilliii** [comment]
In theory if auto connect is configured it should do the same thing on first boot up of the pi.

**Comment by devilhunter84** [comment]
save connection settings and autoconnect on start checkboxes are checked. 
Upon power on the Pi boots up and takes about a minute to connect to the printer. Printer restarts again when OctoPrint finally connects, but the display only says 'Prusa MK3 ready'. 
Perhaps OctoPrint minimizes plugin activity on start to avoid slowness...

**Comment by devilhunter84** [comment]
Ok, setting up a new octopi image on a sd card and installing the plugin worked. 
After a Pi restart the IP address shows up in the display. 
Will investigate. 

Perhaps a setting somewhere causes this. I am connected via a network cable now instead of wifi, perhaps that has something to do with that.

**Comment by devilhunter84** [comment]
So far i've found out that it sometimes works (like 2 out of 8 times) when the Pi is connected to wifi, and it works every time when the Pi is connected over a ethernet cable. 

Also another weird thing here is that if both are connected (wifi + ethernet) the plugin will display the wifi address in the printer's display.

**Comment by jneilliii** [comment]
Thanks for all that leg work. Curious if your powering both up at the same time. There's a chance the wifi isn't as consistent because it's connection isn't initialized completely while the octoprint daemon is loaded, not really sure. I personally don't use the plugin because I have a reserved dhcp address for mine to allow for remote access.

**Comment by devilhunter84** [comment]
Restarting OctoPrint once after it has booted up shows the IP in the display, so something does not work during a cold start. 

Is there any way to call the script from the command line?
I could make a delayed bash script for this

**Comment by jneilliii** [comment]
Ok, just pushed a new branch that will allow you to set a delay as well as added monitoring of the ConnectivityChanged event. to set the delay update the plugins section of your config.yaml with the following; timing is in seconds.  
```
  ipOnConnect:
    delay: 30
```
Use this url to install in plugin manager of OctoPrint.

https://github.com/jneilliii/OctoPrint-ipOnConnect/archive/0.2.0.zip

If this fixes your problem, I'll add a settings interface to allow for changing the value and then push a new release to the master branch.

**Comment by devilhunter84** [comment]
Hah! That did the trick.
Works every time on a cold boot now. 

Thanks for your quick fix, even if the plugin is now 2 years old.

**Comment by jneilliii** [comment]
Cool, I'll make the additional updates tonight and push the new version.

**Comment by jneilliii** [comment]
Issue hopefully fully resolved with latest 0.2.0 release.
