### ISSUE TITLE
Firmware upgrade - timeout

### ISSUE THREAD

**Issue by petrjac** [jneilliii/OctoPrint-ipOnConnect#4]
Hello,

I tried to upgrade firmware on my Prusa MK3 via https://github.com/OctoPrint/OctoPrint-FirmwareUpdater and the process timeouted many times...

Finally helped me to dissable the *ipOnConnect* plugin, than upgrade firmware succeeded.

Maybe someone could have similar issue and be able to reproduce..

Thank you;)

Version:
OctoPrint version : 1.3.8
OctoPi version    : 0.14.0
ipOnConnect (0.2.0)
Firmware Updater (1.0.0)

**Comment by jneilliii** [comment]
That is strange.  I don't know of any reason why this plugin would interfere with that one.  @foosel may be able to assist.  I'll post a cross-issue on that plugin if you haven't already.

**Comment by foosel** [comment]
No idea from my side for now.
