### ISSUE TITLE
Missing last digit of the Address

### ISSUE THREAD

**Issue by sweetgman** [jneilliii/OctoPrint-ipOnConnect#6]
can you add an option to include an extra digit at the end to support printers like the Anet E10. works fine on my Anet A8 fine.

![image](https://user-images.githubusercontent.com/44832527/48120483-3b91df00-e240-11e8-8ed8-64418e6b587e.png)

Works fine for another plugin

![image](https://user-images.githubusercontent.com/44832527/48120564-785dd600-e240-11e8-9598-287ec014ef05.png)

**Comment by OllisGit** [comment]
Thx, a lot!
